name: CI setup with JDK19 and Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK v19
      uses: actions/setup-java@v2  
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Run Maven tests
      run: mvn test
