name: CI setup with JDK19 and Maven

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
       - name: setup JDK v19
       uses: actions/setup-java@v3
       -name: Checkout code
       uses: actions/setup-java@v3
       with:
          java-version: 19

        -name: Run maven test
        run: mvn test

       
        
